name: Build
on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv

      - name: Setup venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install buildozer

      - name: Build APK
        run: |
          source venv/bin/activate
          cd /github/workspace
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: /github/workspace/bin/*.apk